{{b SEPARATOR}}, {{/b}}
{{b COLUMN}}{{v NAME/}} {{v TYPE/}}{{v DEFAULT}}{{/v}}{{v NULLABLE}}{{/v}}{{v CUSTOM_ATTRIBUTES}}{{/v}}{{/b}}
{{b NULL}} NULL{{/b}}
{{b NOTNULL}} NOT NULL{{/b}}
{{b DEFAULT}} DEFAULT {{v V/}}{{/b}}
{{b CUSTOM_ATTRIBUTES}} {{v V/}}{{/b}}
{{b PRIMARY_KEY}}{{v PRIMARY_KEY_NAME}}{{/v}}PRIMARY KEY ({{v COLUMN_NAMES/}}){{/b}}
{{b FOREIGN_KEY}}{{v FOREIGN_KEY_NAME}}{{/v}}FOREIGN KEY ({{v LOCAL_COLUMN_NAMES/}}) REFERENCES {{v FOREIGN_TABLE/}} ({{v FOREIGN_COLUMN_NAMES/}}){{v VIOLATION_ACTIONS}}{{/v}}{{b ON_DELETE}} ON DELETE {{v ON_DELETE_ACTION/}}{{/b}}{{b ON_UPDATE}}{{/b}}{{/b}}
{{b UNIQUE_CONSTRAINT}}{{v UNIQUE_CONSTRAINT_NAME}}{{/v}}UNIQUE ({{v COLUMN_NAMES/}}){{/b}}
{{b CHECK}}{{v CHECK_NAME}}{{/v}}CHECK ({{v EXPRESSION/}}){{/b}}
{{b PRIMARY_KEY_NAME}}CONSTRAINT {{v NAME/}} {{/b}}
{{b FOREIGN_KEY_NAME}}CONSTRAINT {{v NAME/}} {{/b}}
{{b UNIQUE_CONSTRAINT_NAME}}CONSTRAINT {{v NAME/}} {{/b}}
{{b CHECK_NAME}}CONSTRAINT {{v NAME/}} {{/b}}
{{b ON_UPDATE_NOACTION}}{{/b}}
{{b ON_UPDATE_RESTRICT}}{{/b}}
{{b ON_UPDATE_CASCADE}}{{/b}}
{{b ON_UPDATE_SETNULL}}{{/b}}
{{b ON_UPDATE_SETDEFAULT}}{{/b}}
{{b ON_DELETE_NOACTION}}{{/b}}
{{b ON_DELETE_RESTRICT}}{{/b}}
{{b ON_DELETE_CASCADE}}CASCADE{{/b}}
{{b ON_DELETE_SETNULL}}SET NULL{{/b}}
{{b ON_DELETE_SETDEFAULT}}{{/b}}
{{b ADD_COLUMN}}ALTER TABLE {{v TABLE/}} ADD ({{v COLUMN_DEF/}}){{/b}}
{{b DROP_COLUMN}}ALTER TABLE {{v TABLE/}} DROP COLUMN {{v NAME/}}{{/b}}
{{b RENAME_COLUMN}}ALTER TABLE {{v TABLE/}} RENAME COLUMN {{v NAME/}} TO {{v NEW_NAME/}}{{/b}}
{{b ALTER_COLUMN_TYPE}}ALTER TABLE {{v TABLE/}} MODIFY ({{v NAME/}} {{v TYPE/}}{{v DEFAULT}}{{/v}}{{v NULLABLE}}{{/v}}{{v CUSTOM_ATTRIBUTES}}{{/v}}){{/b}}
{{b ALTER_COLUMN_NULL}}ALTER TABLE {{v TABLE/}} MODIFY ({{v NAME/}} NULL){{/b}}
{{b ALTER_COLUMN_NOTNULL}}ALTER TABLE {{v TABLE/}} MODIFY ({{v NAME/}} NOT NULL){{/b}}
{{b ALTER_COLUMN_DEFAULT}}ALTER TABLE {{v TABLE/}} MODIFY ({{v NAME/}} DEFAULT {{v V/}}){{/b}}
{{b ALTER_COLUMN_DROP_DEFAULT}}ALTER TABLE {{v TABLE/}} MODIFY ({{v NAME/}} DEFAULT NULL){{/b}}
{{b ADD_CONSTRAINT}}ALTER TABLE {{v TABLE/}} ADD {{v CONSTRAINT_DEF/}}{{/b}}
{{b DROP_CONSTRAINT}}ALTER TABLE {{v TABLE/}} DROP CONSTRAINT {{v NAME/}}{{/b}}
{{b DROP_PRIMARY_KEY}}ALTER TABLE {{v TABLE/}} DROP PRIMARY KEY{{/b}}
{{b RENAME_TABLE}}ALTER TABLE {{v TABLE/}} RENAME TO {{v NEW_NAME/}}{{/b}}
