{{b SEPARATOR}}, {{/b}}
{{b COLUMN}}{{v NAME/}} {{v TYPE/}}{{v DEFAULT}}{{/v}}{{v NULLABLE}}{{/v}}{{v CUSTOM_ATTRIBUTES}}{{/v}}{{/b}}
{{b NULL}} {{/b}}
{{b NOTNULL}} NOT NULL{{/b}}
{{b DEFAULT}} DEFAULT {{v V/}}{{/b}}
{{b CUSTOM_ATTRIBUTES}} {{v V/}}{{/b}}
{{b PRIMARY_KEY}}{{v PRIMARY_KEY_NAME}}{{/v}}PRIMARY KEY ({{v COLUMN_NAMES/}}){{/b}}
{{b FOREIGN_KEY}}{{v FOREIGN_KEY_NAME}}{{/v}}FOREIGN KEY ({{v LOCAL_COLUMN_NAMES/}}) REFERENCES {{v FOREIGN_TABLE/}} ({{v FOREIGN_COLUMN_NAMES/}}){{v VIOLATION_ACTIONS}}{{/v}}{{b ON_DELETE}} ON DELETE {{v ON_DELETE_ACTION/}}{{/b}}{{b ON_UPDATE}} ON UPDATE {{v ON_UPDATE_ACTION/}}{{/b}}{{/b}}
{{b UNIQUE_CONSTRAINT}}{{v UNIQUE_CONSTRAINT_NAME}}{{/v}}UNIQUE ({{v COLUMN_NAMES/}}){{/b}}
{{b CHECK}}{{v CHECK_NAME}}{{/v}}CHECK ({{v EXPRESSION/}}){{/b}}
{{b PRIMARY_KEY_NAME}}CONSTRAINT {{v NAME/}} {{/b}}
{{b FOREIGN_KEY_NAME}}CONSTRAINT {{v NAME/}} {{/b}}
{{b UNIQUE_CONSTRAINT_NAME}}CONSTRAINT {{v NAME/}} {{/b}}
{{b CHECK_NAME}}CONSTRAINT {{v NAME/}} {{/b}}
{{b ON_UPDATE_NOACTION}}NO ACTION{{/b}}
{{b ON_UPDATE_RESTRICT}}RESTRICT{{/b}}
{{b ON_UPDATE_CASCADE}}{{/b}}
{{b ON_UPDATE_SETNULL}}{{/b}}
{{b ON_UPDATE_SETDEFAULT}}{{/b}}
{{b ON_DELETE_NOACTION}}NO ACTION{{/b}}
{{b ON_DELETE_RESTRICT}}RESTRICT{{/b}}
{{b ON_DELETE_CASCADE}}CASCADE{{/b}}
{{b ON_DELETE_SETNULL}}SET NULL{{/b}}
{{b ON_DELETE_SETDEFAULT}}{{/b}}
{{b ADD_COLUMN}}ALTER TABLE {{v TABLE/}} ADD COLUMN {{v COLUMN_DEF/}}{{/b}}
{{b DROP_COLUMN}}ALTER TABLE {{v TABLE/}} DROP COLUMN {{v NAME/}}{{/b}}
{{b RENAME_COLUMN}}RENAME COLUMN {{v TABLE/}}.{{v NAME/}} TO {{v NEW_NAME/}}{{/b}}
{{b ALTER_COLUMN_TYPE}}ALTER TABLE {{v TABLE/}} ALTER COLUMN {{v NAME/}} SET DATA TYPE {{v TYPE/}}{{/b}}
{{b ALTER_COLUMN_NULL}}ALTER TABLE {{v TABLE/}} ALTER COLUMN {{v NAME/}} NULL{{/b}}
{{b ALTER_COLUMN_NOTNULL}}ALTER TABLE {{v TABLE/}} ALTER COLUMN {{v NAME/}} NOT NULL{{/b}}
{{b ALTER_COLUMN_DEFAULT}}ALTER TABLE {{v TABLE/}} ALTER COLUMN {{v NAME/}} DEFAULT {{v V/}}{{/b}}
{{b ALTER_COLUMN_DROP_DEFAULT}}{{/b}}
{{b ADD_CONSTRAINT}}ALTER TABLE {{v TABLE/}} ADD {{v CONSTRAINT_DEF/}}{{/b}}
{{b DROP_CONSTRAINT}}ALTER TABLE {{v TABLE/}} DROP CONSTRAINT {{v NAME/}}{{/b}}
{{b DROP_PRIMARY_KEY}}{{/b}}
{{b RENAME_TABLE}}RENAME TABLE {{v TABLE/}} TO {{v NEW_NAME/}}{{/b}}
